### ISSUE TITLE
how to solve the following error

### ISSUE THREAD

**Issue by fadwaahmed** [ucb-sts/sts#49]
Exception: Please shut down the controller which is running on port 6633:
Active Internet connections (servers and established)
tcp6       0      0 :::6633                 :::\*                    LISTEN      9457/java

**Comment by ahassany** [comment]
Please redirect question related to running STS to sts-dev@googlegroups.com. The Github Issues is meant to report bugs or report features.

**Comment by fadwaahmed** [comment]
I can not connect to  sts-dev@googlegroups.com

**Comment by colin-scott** [comment]
The error says that you have a controller process running at port 6633. You need to kill that process.

Try: pkill -f pox

Replace "pox" with the name of your controller

**Comment by fadwaahmed** [comment]
the following error appear
pkill: killing pid 673 failed: Operation not permitted

**Comment by fadwaahmed** [comment]
the follwing error appear:pkill: killing pid 673 failed: Operation not permitted

```
  From: Colin Scott <notifications@github.com>
```

 To: ucb-sts/sts sts@noreply.github.com 
Cc: fadwaahmed fadwauae@yahoo.com 
 Sent: Friday, August 14, 2015 8:23 PM
 Subject: Re: [sts] how to solve the following error (#49)

The error says that you have a controller process running at port 6633. You need to kill that process.Try: pkill -f poxReplace "pox" with the name of your controller—

**Comment by colin-scott** [comment]
"Operation not permitted" means you need to have root access. Try running
it like this:

$ sudo pkill -f pox
