### ISSUE TITLE
listen to POX openflow packetin how to get ip from event

### ISSUE THREAD

**Issue by xinwei9103** [ucb-sts/sts#50]
after the _handler_PacketIn got the event when listen to the openflow, how to get scr and dst ip address from event?

**Comment by ahassany** [comment]
```
def _handle_PacketIn (self, event):
  packet = event.parsed
  if isinstance(packet.next, ipv4):
    ip_packet = packet.next
    print ip_packet.srcip, ip_packet.dstip
```

You can see detailed example at: https://github.com/ucb-sts/pox/blob/debugger/pox/forwarding/l3_learning.py or refer to the POX documentation for more details.
